Create page fix
joac1144/ProjectIT pull request #39
Opened 2023-04-07 20:08 UTC by joac1144

2023-04-07 20:09 UTC, joac1144 commented on src/ProjectIT/Client/ProjectIT.Client.csproj
Was automatically added by VS for Mac. Does not seem to break anything

2023-04-07 20:09 UTC, joac1144 commented on src/ProjectIT/Server/ProjectIT.Server.csproj
Was automatically added by VS for Mac. Does not seem to break anything

2023-04-07 22:37 UTC, Alaa0129 requested changes

2023-04-07 22:37 UTC, Alaa0129 commented on src/ProjectIT/Tests/Repository.Tests/TopicsRepositoryTests.cs
> +    public async void ReadAllAsync_ReturnsAllProjects()
Fix method name to match test

2023-04-07 22:37 UTC, Alaa0129 commented on src/ProjectIT/Tests/Controller.Tests/TopicsControllerTests.cs
> +    public async void GetAll_ReturnsProjects()
Fix method name to match test

2023-04-07 22:56 UTC, joac1144 commented on src/ProjectIT/Tests/Repository.Tests/TopicsRepositoryTests.cs
> +    public async void ReadAllAsync_ReturnsAllProjects()
Fixed

2023-04-07 22:56 UTC, joac1144 commented on src/ProjectIT/Tests/Controller.Tests/TopicsControllerTests.cs
> +    public async void GetAll_ReturnsProjects()
Fixed

2023-04-07 23:19 UTC, Alaa0129 approved these changes

2023-04-08 01:16 UTC, Alaa0129 approved these changes

2023-04-08 01:23 UTC, merged