FE-create request almost done
joac1144/ProjectIT pull request #42
Opened 2023-04-10 14:20 UTC by Mohammadhasham1999

Done, but the css for request-title (line 59 in CreateRequestPage.razor) and request-description (line 62 in CreateRequestPage.razor) is not applied which is why explicit styles are added. How to fix that?

2023-04-10 19:00 UTC, Alaa0129 requested changes
Merge with main and setup migrations before pushing to main.. Check README file for instructions.

2023-04-12 14:00 UTC, joac1144 approved these changes

2023-04-14 00:55 UTC, Alaa0129 approved these changes

2023-04-14 01:36 UTC, joac1144 approved these changes

2023-04-14 11:38 UTC, merged