Htmltags fixses
joac1144/ProjectIT pull request #84
Opened 2023-09-28 23:48 UTC by Emdadollah

2023-09-29 10:44 UTC, joac1144 requested changes

2023-09-29 10:44 UTC, joac1144 commented on src/ProjectIT/Client/Pages/Supervisors/CreateProject/CreateProjectPage.razor.cs
>              await JSRuntime.InvokeAsync<string>("alert", "Project description should not be more than 2400 characters.");
2400 != 4800

2023-09-29 10:44 UTC, joac1144 commented on src/ProjectIT/Client/Pages/Supervisors/CreateProject/CreateProjectPage.razor.cs
> +        var strippedString = _htmlHepler.RemoveFromText(newProject.DescriptionHtml);
hepler --> helper

2023-09-29 10:44 UTC, joac1144 commented on src/ProjectIT/Client/Shared/Helpers/HTMLTags.cs
> +namespace ProjectIT.Client.Shared.Helpers
Follow .NET 6+ way to declare namespace

2023-09-29 10:44 UTC, joac1144 commented on src/ProjectIT/Client/Shared/Helpers/HTMLTags.cs
> +    public class HTMLTags
Make class and RemoveFromText static. 

Use class with HTMLTags.RemoveFromText(...) instead of creating an instance of it

2023-09-29 10:44 UTC, joac1144 commented on src/ProjectIT/Client/Shared/Helpers/HTMLTags.cs
> +            try
Why is a try-catch needed here?

2023-10-01 12:44 UTC, joac1144 approved these changes

2023-10-01 13:58 UTC, Alaa0129 requested changes
Need to be reviewed and fixed properly

2023-10-02 09:07 UTC, closed without merging

2023-10-02 09:07 UTC, Alaa0129 commented
merged into another branch